DELETE FROM `command`;
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.24 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2012-06-10 22:21:38
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;
-- Dumping data for table world.command: 410 rows
/*!40000 ALTER TABLE `command` DISABLE KEYS */;
INSERT INTO `command` (`name`, `security`, `help`) VALUES
	('account create', 4, 'Syntax: .account create $account $password\r\n\r\nCreate account and set password to it.'),
	('account delete', 4, 'Syntax: .account delete $account\r\n\r\nDelete account with all characters.'),
	('account lock', 0, 'Syntax: .account lock [on|off]\r\n\r\nAllow login from account only from current used IP or remove this requirement.'),
	('account onlinelist', 4, 'Syntax: .account onlinelist\r\n\r\nShow list of online accounts.'),
	('account password', 0, 'Syntax: .account password $old_password $new_password $new_password\r\n\r\nChange your account password.'),
	('account set addon', 3, 'Syntax: .account set addon [$account] #addon\r\n\r\nSet user (possible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk.'),
	('account set gmlevel', 4, 'Syntax: .account set gmlevel [$account] #level [#realmid]\r\n\r\nSet the security level for targeted player (can\'t be used at self) or for account $name to a level of #level on the realm #realmID.\r\n\r\n#level may range from 0 to 3.\r\n\r\n#reamID may be -1 for all realms.'),
	('account set password', 4, 'Syntax: .account set password $account $password $password\r\n\r\nSet password for account.'),
	('account set', 3, 'Syntax: .account set $subcommand\nType .account set to see the list of possible subcommands or .help account set $subcommand to see info on subcommands'),
	('account', 0, 'Syntax: .account\r\n\r\nDisplay the access level of your account.'),
	('additem', 0, 'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\n\r\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added.\r\n.'),
	('additemset', 0, 'Syntax: .additemset #itemsetid\r\n\r\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.'),
	('systemannounce', 3, 'Syntax: .announce $MessageToBroadcast\r\n\r\nSend a global message to all players online in chat log.'),
	('aura', 0, 'Syntax: .aura #spellid\r\n\r\nAdd the aura from spell #spellid to the selected Unit.'),
	('ban account', 3, 'Syntax: .ban account $Name $bantime $reason\r\nBan account kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('ban character', 3, 'Syntax: .ban character $Name $bantime $reason\nBan character and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('ban ip', 3, 'Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('ban', 3, 'Syntax: .ban $subcommand\nType .ban to see the list of possible subcommands or .help ban $subcommand to see info on subcommands'),
	('baninfo account', 3, 'Syntax: .baninfo account $accountid\r\nWatch full information about a specific ban.'),
	('baninfo character', 3, 'Syntax: .baninfo character $charactername \r\nWatch full information about a specific ban.'),
	('baninfo ip', 3, 'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ban.'),
	('baninfo', 3, 'Syntax: .baninfo $subcommand\nType .baninfo to see the list of possible subcommands or .help baninfo $subcommand to see info on subcommands'),
	('bank', 3, 'Syntax: .bank\r\n\r\nShow your bank inventory.'),
	('banlist account', 3, 'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.'),
	('banlist character', 3, 'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern. Pattern required.'),
	('banlist ip', 3, 'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.'),
	('banlist', 3, 'Syntax: .banlist $subcommand\nType .banlist to see the list of possible subcommands or .help banlist $subcommand to see info on subcommands'),
	('bindsight', 3, 'Syntax: .bindsight\r\n\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.'),
	('cast back', 3, 'Syntax: .cast back #spellid [triggered]\r\n  Selected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast dist', 3, 'Syntax: .cast dist #spellid [#dist [triggered]]\r\n  You will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.'),
	('cast self', 0, 'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast target', 3, 'Syntax: .cast target #spellid [triggered]\r\n  Selected target will cast #spellid to his victim. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast', 0, 'Syntax: .cast #spellid [triggered]\r\n  Cast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('character recustomize', 0, 'Syntax: .character customize [$name]\r\n\r\nMark selected in game or by $name in command character for customize at next login.'),
	('character erase', 4, 'Syntax: .character erase $name\r\n\r\nDelete character $name. Character finally deleted in case any deleting options.'),
	('character level', 0, 'Syntax: .character level [$playername] [#level]\r\n\r\nSet the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.'),
	('character rename', 0, 'Syntax: .character rename [$name]\r\n\r\nMark selected in game or by $name in command character for rename at next login.'),
	('cheat power', 0, 'Syntax: .cheat power\r\nWhen enabled, you don\'t use mana, power, runes, or energy.'),
	('combatstop', 2, 'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.'),
	('cometome', 3, 'SYntax: .cometome $parameter\nMake selected creature come to your current location (new position not saved to DB).'),
	('commands', 0, 'Syntax: .commands\r\n\r\nDisplay a list of available commands for your account level.'),
	('clearcooldowns', 3, 'Syntax: .cooldown [#spell_id]\r\n\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).'),
	('dealdamage', 3, 'Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.'),
	('debug arena', 3, 'Syntax: .debug arena\r\n\r\nToggle debug mode for arenas. In debug mode GM can start arena with single player.'),
	('debug bg', 3, 'Syntax: .debug bg\r\n\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player.'),
	('debug Mod32Value', 3, 'Syntax: .debug Mod32Value #field #value\r\n\r\nAdd #value to field #field of your character.'),
	('debug play cinematic', 1, 'Syntax: .debug play cinematic #cinematicid\r\n\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.\r\n'),
	('debug play movie', 1, 'Syntax: .debug play movie #movieid\r\n\r\nPlay movie #movieid for you.'),
	('debug play sound', 1, 'Syntax: .debug play sound #soundid\r\n\r\nPlay sound with #soundid.\r\nSound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...'),
	('debug', 1, 'Syntax: .debug $subcommand\nType .debug to see the list of possible subcommands or .help debug $subcommand to see info on subcommands'),
	('demorph', 0, 'Syntax: .demorph\r\n\r\nDemorph the selected player.'),
	('kill', 0, 'Syntax: .die\r\n\r\nKill the selected player. If no player is selected, it will kill you.'),
	('dismount', 0, 'Syntax: .dismount\r\n\r\nDismount you, if you are mounted.'),
	('getdistance', 3, 'Syntax: .distance\r\n\r\nDisplay the distance from your character to the selected creature.'),
	('event activelist', 2, 'Syntax: .event activelist\r\nShow list of currently active events.'),
	('event start', 2, 'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).'),
	('event stop', 2, 'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).'),
	('event', 2, 'Syntax: .event #event_id\r\nShow details about event with #event_id.'),
	('explorecheat', 0, 'Syntax: .cheat explore #flag\r\n\r\nReveal  or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\n\r\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps.'),
	('flusharenapoints', 3, 'Syntax: .flusharenapoints\r\n\r\nUse it to distribute arena points based on arena team ratings, and start a new week.'),
	('freeze', 1, 'Syntax: .freeze (#player)\r\n"Freezes" #player and disables his chat. When using this without #name it will freeze your target.'),
	('gm chat', 1, 'Syntax: .gm chat [on/off]\r\n\r\nEnable or disable chat GM MODE (show gm badge in messages) or show current state of on/off not provided.'),
	('gm fly', 3, 'Syntax: .gm fly [on/off]\r\nEnable/disable gm fly mode.'),
	('gm ingame', 0, 'Syntax: .gm ingame\r\n\r\nDisplay a list of available in game Game Masters.'),
	('gm list', 0, 'Syntax: .gm list\r\n\r\nDisplay a list of all Game Masters accounts and security levels.'),
	('gm invisible', 1, 'Syntax: .gm visible on/off\r\n\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.'),
	('gm', 0, 'Syntax: .gm [on/off]\r\n\r\nEnable or Disable in game GM MODE or show current state of on/off not provided.'),
	('gmannounce', 1, 'Syntax: .gmnameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.'),
	('gmnotify', 1, 'Syntax: .gmnotify $notification\r\nDisplays a notification on the screen of all online GM\'s.'),
	('go creature', 0, 'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.'),
	('go graveyard', 0, 'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.'),
	('go grid', 0, 'Syntax: .go grid #gridX #gridY [#mapId]\r\n\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).'),
	('go object', 0, 'Syntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid'),
	('go taxinode', 0, 'Syntax: .go taxinode #taxinode\r\n\r\nTeleport player to taxinode coordinates. You can look up zone using .lookup taxinode $namepart'),
	('go ticket', 0, 'Syntax: .go ticket #ticketid\r\nTeleports the user to the location where $ticketid was created.'),
	('go trigger', 0, 'Syntax: .go trigger #trigger_id\r\n\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.'),
	('worldport', 0, 'Syntax: .worldport #x #y #z [#mapid]\r\n\r\nTeleport player to point with (#x,#y,#z) coordinates at ground(water) level at map #mapid or same map if #mapid not provided.'),
	('go zonexy', 0, 'Syntax: .go zonexy #x #y [#zone]\r\n\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart'),
	('go', 0, 'Syntax: .go $subcommand\nType .go to see the list of possible subcommands or .help go $subcommand to see info on subcommands'),
	('gobject activate', 0, 'Syntax: .gobject activate #guid\r\n\r\nActivates an object like a door or a button.'),
	('gobject delete', 0, 'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.'),
	('gobject move', 0, 'Syntax: .gobject move #goguid [#x #y #z]\r\n\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).'),
	('toggle summon', 0, 'Syntax: .toggle summon\r\nIf enabled, players can\'t summon you. (Does not affect admins ability to summon you.)'),
	('gobject spawn', 0, 'Adds a temporary gameobject that is not saved to DB.'),
	('gobject select', 0, 'Syntax: .gobject target [#go_id|#go_name_part]\r\n\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.'),
	('gobject set phase', 0, 'Syntax: .gobject set phase #guid #phasemask\r\n\r\nGameobject with DB guid #guid phasemask changed to #phasemask with related world vision update for players. Gameobject state saved to DB and persistent.'),
	('gobject rotate', 0, 'Syntax: .gobject turn #goguid \r\n\r\nSet for gameobject #goguid orientation same as current character orientation.'),
	('gobject', 0, 'Syntax: .gobject $subcommand\nType .gobject to see the list of possible subcommands or .help gobject $subcommand to see info on subcommands'),
	('summon', 0, 'Syntax: .summon [$charactername]\r\n\r\nTeleport the given character to you. Character can be offline.'),
	('gps', 0, 'Syntax: .gps [$name|$shift-link]\r\n\r\nDisplay the position information for a selected character or creature (also if player name $name provided then for named player, or if creature/gameobject shift-link provided then pointed creature/gameobject if it loaded). Position information includes X, Y, Z, and orientation, map Id and zone Id'),
	('groupsummon', 1, 'Syntax: .groupsummon [$charactername]\r\n\r\nTeleport the given character and his group to you. Teleported only online characters but original selected group member can be offline.'),
	('guid', 0, 'Syntax: .guid\r\n\r\nDisplay the GUID for the selected character.'),
	('guild create', 0, 'Syntax: .guild create [$GuildLeaderName] "$GuildName"\r\n\r\nCreate a guild named $GuildName with the player $GuildLeaderName (or selected) as leader.  Guild name must in quotes.'),
	('guild delete', 0, 'Syntax: .guild delete "$GuildName"\r\n\r\nDelete guild $GuildName. Guild name must in quotes.'),
	('guild invite', 0, 'Syntax: .guild invite [$CharacterName] "$GuildName"\r\n\r\nAdd player $CharacterName (or selected) into a guild $GuildName. Guild name must in quotes.'),
	('guild rank', 0, 'Syntax: .guild rank [$CharacterName] #Rank\r\n\r\nSet for player $CharacterName (or selected) rank #Rank in a guild.'),
	('guild uninvite', 0, 'Syntax: .guild uninvite [$CharacterName]\r\n\r\nRemove player $CharacterName (or selected) from a guild.'),
	('guild', 0, 'Syntax: .guild $subcommand\nType .guild to see the list of possible subcommands or .help guild $subcommand to see info on subcommands'),
	('help', 0, 'Syntax: .help [$command]\r\n\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.'),
	('hidearea', 3, 'Syntax: .hidearea #areaid\r\n\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.'),
	('honor add', 0, 'Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained today) to the selected player.'),
	('honor add kill', 0, 'Syntax: .honor add kill\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)'),
	('honor update', 0, 'Syntax: .honor update\r\n\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.'),
	('honor', 0, 'Syntax: .honor $subcommand\nType .honor to see the list of possible subcommands or .help honor $subcommand to see info on subcommands'),
	('instance listbinds', 3, 'Syntax: .instance listbinds\r\n  Lists the binds of the selected player.'),
	('instance savedata', 3, 'Syntax: .instance savedata\r\n  Save the InstanceData for the current player\'s map to the DB.'),
	('instance stats', 3, 'Syntax: .instance stats\r\n  Shows statistics about instances.'),
	('instance unbind', 3, 'Syntax: .instance unbind <mapid|all> [difficulty]\r\n  Clear all/some of player\'s binds'),
	('instance', 0, 'Syntax: .instance $subcommand\nType .instance to see the list of possible subcommands or .help instance $subcommand to see info on subcommands'),
	('kick', 2, 'Syntax: .kick [$charactername] [$reason]\r\n\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is "No Reason".'),
	('learn all my talents', 0, 'Syntax: .learn all my talents\r\n\r\nLearn all talents (and spells with first rank learned as talent) available for his class.'),
	('learn all my spells', 0, 'Syntax: .learn all my spells\r\n\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.'),
	('learn all my pettalents', 0, 'Syntax: .learn all my pettalents\r\n\r\nLearn all talents for your pet available for his creature type (only for hunter pets).'),
	('learn all my class', 0, 'Syntax: .learn all my class\r\n\r\nLearn all spells and talents available for his class.'),
	('learn all gm', 0, 'Syntax: .learn all gm\r\n\r\nLearn all default spells for Game Masters.'),
	('learn all lang', 0, 'Syntax: .learn all lang\r\n\r\nLearn all languages'),
	('learn all default', 0, 'Syntax: .learn all default [$playername]\r\n\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.'),
	('learn', 0, 'Syntax: .learn #spell [all]\r\n\r\nSelected character learn a spell of id #spell. If \'all\' provided then all ranks learned.'),
	('learn all', 0, 'Syntax: .learn all\r\n\r\nLearn all big set different spell maybe useful for Administaror.'),
	('learn all crafts', 0, 'Syntax: .learn crafts\r\n\r\nLearn all professions and recipes.'),
	('levelup', 0, 'Syntax: .levelup [$playername] [#numberoflevels]\r\n\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.'),
	('linkgrave', 3, 'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\n\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).'),
	('list auras', 0, 'Syntax: .list auras\nList auras (passive and active) of selected creature or player. If no creature or player is selected, list your own auras.'),
	('list creature', 0, 'Syntax: .list creature #creature_id [#max_count]\r\n\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.'),
	('list item', 0, 'Syntax: .list item #item_id [#max_count]\r\n\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.'),
	('list object', 0, 'Syntax: .list object #gameobject_id [#max_count]\r\n\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.'),
	('list', 0, 'Syntax: .list $subcommand\nType .list to see the list of possible subcommands or .help list $subcommand to see info on subcommands'),
	('list frozen', 1, 'Syntax: .listfreeze\r\n\r\nSearch and output all frozen players.'),
	('waypoint reload', 3, 'Syntax: .wp reload $pathid\nLoad path changes ingame - IMPORTANT: must be applied first for new paths before .wp load #pathid '),
	('reload spell_group', 3, 'Syntax: .reload spell_group\nReload spell_group table.'),
	('lookup area', 0, 'Syntax: .lookup area $namepart\r\n\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.'),
	('lookup creature', 0, 'Syntax: .lookup creature $namepart\r\n\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.'),
	('lookup event', 0, 'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.'),
	('lookup faction', 0, 'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.'),
	('lookup item', 0, 'Syntax: .lookup item $itemname\r\n\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.'),
	('lookup itemset', 0, 'Syntax: .lookup itemset $itemname\r\n\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.'),
	('lookup map', 0, 'Syntax: .lookup map $namepart\r\n\r\nLooks up a map by $namepart, and returns all matches with their map ID\'s.'),
	('lookup object', 0, 'Syntax: .lookup object $objname\r\n\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.'),
	('lookup player account', 2, 'Syntax: .lookup player account $account ($limit) \r\n\r\n Searchs players, which account username is $account with optional parametr $limit of results.'),
	('lookup player email', 2, 'Syntax: .lookup player email $email ($limit) \r\n\r\n Searchs players, which account email is $email with optional parametr $limit of results.'),
	('lookup player ip', 2, 'Syntax: .lookup player ip $ip ($limit) \r\n\r\n Searchs players, which account ast_ip is $ip with optional parametr $limit of results.'),
	('lookup quest', 0, 'Syntax: .lookup quest $namepart\r\n\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.'),
	('lookup skill', 0, 'Syntax: .lookup skill $$namepart\r\n\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.'),
	('lookup spell', 0, 'Syntax: .lookup spell $namepart\r\n\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.'),
	('lookup taxinode', 0, 'Syntax: .lookup taxinode $substring\r\n\r\nSearch and output all taxinodes with provide $substring in name.'),
	('lookup port', 0, 'Syntax: .lookup tele $substring\r\n\r\nSearch and output all .tele command locations with provide $substring in name.'),
	('lookup', 0, 'Syntax: .lookup $subcommand\nType .lookup to see the list of possible subcommands or .help lookup $subcommand to see info on subcommands'),
	('maxskill', 0, 'Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum values for its current level.'),
	('modify arenapoints', 0, 'Syntax: .modify arena #value\r\nAdd $amount arena points to the selected player.'),
	('modify speed', 0, 'Syntax: .modify aspeed #rate\r\n\r\nModify all speeds -run,swim,run back,swim back- of the selected player to "normalbase speed for this move type"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.'),
	('modify bit', 0, 'Syntax: .modify bit #field #bit\r\n\r\nToggle the #bit bit of the #field field for the selected player. If no player is selected, modify your character.'),
	('cheat triggerpass', 0, 'Syntax: .cheat triggerpass\r\nWhen enabled, you don\'t need to be in a raid group to enter a raid.'),
	('toggle modify', 0, 'Syntax: .toggle modify\r\nIf enabled, players can\'t use commands on you. (Does not affect admins use of commands on you.)'),
	('modify drunkstate', 0, 'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.'),
	('modify energy', 0, 'Syntax: .modify energy #energy\r\n\r\nModify the energy of the selected player. If no player is selected, modify your energy.'),
	('modify faction', 0, 'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\n\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.'),
	('toggle appear', 0, 'Syntax: .toggle appear\r\nIf enabled, players can\'t appear to you. (Does not affect admins ability to appear to you.)'),
	('modify gender', 0, 'Syntax: .modify gender male/female\r\n\r\nChange gender of selected player.'),
	('modify honor', 0, 'Syntax: .modify honor $amount\r\n\r\nAdd $amount honor points to the selected player.'),
	('modify hp', 0, 'Syntax: .modify hp #newhp\r\n\r\nModify the hp of the selected player. If no player is selected, modify your hp.'),
	('modify mana', 0, 'Syntax: .modify mana #newmana\r\n\r\nModify the mana of the selected player. If no player is selected, modify your mana.'),
	('modify gold', 0, 'Syntax: .modify money #money\r\n.money #money\r\n\r\nAdd or remove money to the selected player. If no player is selected, modify your money.\r\n\r\n #gold can be negative to remove money.'),
	('modify displayid', 0, 'Syntax: .modify morph #displayid\r\n\r\nChange your current model id to #displayid.'),
	('mount', 0, 'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.'),
	('modify phase', 0, 'Syntax: .modify phase #phasemask\r\n\r\nSelected character phasemask changed to #phasemask with related world vision update. Change active until in game phase changed, or GM-mode enable/disable, or re-login. Character pts pasemask update to same value.'),
	('modify rage', 0, 'Syntax: .modify rage #newrage\r\n\r\nModify the rage of the selected player. If no player is selected, modify your rage.'),
	('character setstanding', 0, 'Syntax: .modify rep #repId (#repvalue | $rankname [#delta])\r\nSets the selected players reputation with faction #repId to #repvalue or to $reprank.\r\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\r\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.'),
	('modify runicpower', 0, 'Syntax: .modify runicpower #newrunicpower\r\n\r\nModify the runic power of the selected player. If no player is selected, modify your runic power.'),
	('modify scale', 0, '.modify scale $parameter\nModify size of the selected player to "normal scale"*rate. If no player is selected, modify your size.\n#rate may range from 0.1 to 10.'),
	('cheat god', 0, 'Syntax: .cheat god\r\nWhen enabled, you don\'t take damage.'),
	('cheat casttime', 0, 'Syntax: .cheat casttime\r\n When Enabled, all of your casts are instant.'),
	('cheat cooldown', 0, 'Syntax: .cheat cooldown \r\nWhen Enabled, the GCD doesn\'t affect you.'),
	('cheat fly', 0, 'Syntax: .cheat fly \r\nAllows you to fly.'),
	('nudge x', 0, 'Syntax: .nudge x \r\nMoves you 3 units over on the X axis.'),
	('modify talentpoints', 1, 'Syntax: .modify tp #amount\r\n\r\nSet free talent pointes for selected character or character\'s pet. It will be reset to default expected at next levelup/login/quest reward.'),
	('modify', 0, 'Syntax: .modify $subcommand\nType .modify to see the list of possible subcommands or .help modify $subcommand to see info on subcommands'),
	('movegens', 3, 'Syntax: .movegens\r\n  Show movement generators stack for selected creature or player.'),
	('mute', 2, 'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\n\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.'),
	('announce', 0, 'Syntax: .announce $message.\nSend an announcement to all online players, displaying the name of the sender.'),
	('appear', 0, 'Syntax: .appear [$charactername]\r\n\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait,e.g. when you are in a group. Character can be offline.'),
	('neargrave', 3, 'Syntax: .neargrave [alliance|horde]\r\n\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).'),
	('notify', 2, 'Syntax: .notify $MessageToBroadcast\r\n\r\nSend a global message to all players online in screen.'),
	('npc set phase', 2, 'Syntax: .npc set phase #phasemask\r\n\r\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable..'),
	('npc set movetype', 2, 'Syntax: .npc set movetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.'),
	('npc set model', 2, 'Syntax: .npc set model #displayid\r\n\r\nChange the model id of the selected creature to #displayid.'),
	('npc set link', 2, 'Syntax: .npc set link $creatureGUID\r\n\r\nLinks respawn of selected creature to the condition that $creatureGUID defined is alive.'),
	('npc say', 0, 'Syntax: .npc say $message\nMake selected creature say specified message.'),
	('npc move', 0, 'Syntax: .npc move [#creature_guid]\r\n\r\nMove the targeted creature spawn point to your coordinates.'),
	('npc playemote', 0, 'Syntax: .npc playemote #emoteid\r\n\r\nMake the selected creature emote with an emote of id #emoteid.'),
	('npc follow stop', 0, 'Syntax: .npc follow stop\r\n\r\nSelected creature (non pet) stop follow you.'),
	('npc info', 0, 'Syntax: .npc info\r\n\r\nDisplay a list of details for the selected creature.\r\n\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n\r\n- Field flags, dynamic flags, faction template, \r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.'),
	('npc follow', 0, 'Syntax: .npc follow start\r\n\r\nSelected creature start follow you until death/fight/etc.'),
	('npc set flag', 2, 'Syntax: .npc set flag #npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.'),
	('npc set factionid', 2, 'Syntax: .npc set factionid #factionid\r\n\r\nSet the faction of the selected creature to #factionid.'),
	('npc set level', 2, 'Syntax: .npc set level #level\r\n\r\nChange the level of the selected creature to #level.\r\n\r\n#level may range from 1 to (CONFIG_MAX_PLAYER_LEVEL) + 3.'),
	('npc delete', 0, 'Syntax: .npc delete [#guid]\r\n\r\nDelete creature with guid #guid (or the selected if no guid is provided)'),
	('npc vendor removeitem', 0, 'Syntax: .npc delete item #itemId\r\n\r\nRemove item #itemid from item list of selected vendor.'),
	('npc set allowmove', 0, 'Syntax: .npc set allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented.'),
	('npc set entry', 2, 'Syntax: .npc set entry $entry\nSwitch selected creature with another entry from creature_template. - New creature.id value not saved to DB.'),
	('npc set move', 0, 'Syntax: .npc add move #creature_guid [#waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.'),
	('npc vendor additem', 0, 'Syntax: .npc add item #itemId <#maxcount><#incrtime><#extendedcost>r\r\n\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.'),
	('npc set formation', 0, 'Syntax: .npc add formation $leader\nAdd selected creature to a leader\'s formation.'),
	('npc', 0, 'Syntax: .npc $subcommand\nType .npc to see the list of possible subcommands or .help npc $subcommand to see info on subcommands'),
	('pdump load', 3, 'Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLoad character dump from dump file into character list of $account with saved or $newname, with saved (or first free) or $newguid guid.'),
	('pdump write', 3, 'Syntax: .pdump write $filename $playerNameOrGUID\r\nWrite character dump with name/guid $playerNameOrGUID to file $filename.'),
	('pdump', 3, 'Syntax: .pdump $subcommand\nType .pdump to see the list of possible subcommands or .help pdump $subcommand to see info on subcommands'),
	('pet create', 0, 'Syntax: .pet create\r\n\r\nCreates a pet of the selected creature.'),
	('pet learn', 0, 'Syntax: .pet learn\r\n\r\nLearn #spellid to pet.'),
	('pet unlearn', 0, 'Syntax: .pet unlean\r\n\r\nunLearn #spellid to pet.'),
	('pet', 0, 'Syntax: .pet $subcommand\nType .pet to see the list of possible subcommands or .help pet $subcommand to see info on subcommands'),
	('playerinfo', 2, 'Syntax: .pinfo [$player_name]\r\n\r\nOutput account information for selected player or player find by $player_name.'),
	('server playall', 2, 'Syntax: .playall #soundid\r\n\r\nPlayer a sound to whole server.'),
	('possess', 3, 'Syntax: .possess\r\n\r\nPossesses indefinitely the selected creature.'),
	('quest add', 0, 'Syntax: .quest add #quest_id\r\n\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.'),
	('quest complete', 0, 'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.'),
	('quest remove', 0, 'Syntax: .quest remove #quest_id\r\n\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.'),
	('quest', 0, 'Syntax: .quest $subcommand\nType .quest to see the list of possible subcommands or .help quest $subcommand to see info on subcommands'),
	('modify level', 0, 'Syntax: .modifty level #level\r\nSets the targets level to #level'),
	('reload all quest', 3, 'Syntax: .reload all quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.'),
	('reload all npc', 3, 'Syntax: .reload all npc\nReload npc_option, npc_trainer, npc vendor, points of interest tables.'),
	('reload all loot', 3, 'Syntax: .reload all loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.'),
	('reload all item', 3, 'Syntax: .reload all item\nReload page_text, item_enchantment_table tables.'),
	('reload all locales', 3, 'Syntax: .reload all locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.'),
	('reload all gossips', 3, 'Syntax: .reload all gossips\nReload gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables.'),
	('reload all', 3, 'Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded.'),
	('reload areatrigger_involvedrelation', 3, 'Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table.'),
	('reload areatrigger_tavern', 3, 'Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table.'),
	('reload areatrigger_teleport', 3, 'Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table.'),
	('reload autobroadcast', 3, 'Syntax: .reload autobroadcast\nReload autobroadcast table.'),
	('reload command', 3, 'Syntax: .reload command\nReload command table.'),
	('reload config', 3, 'Syntax: .reload config\r\n\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.'),
	('reload creature_involvedrelation', 3, 'Syntax: .reload creature_involvedrelation\nReload creature_involvedrelation table.'),
	('reload creature_linked_respawn', 2, 'Syntax: .reload creature_linked_respawn\r\nReload creature_linked_respawn table.'),
	('reload creature_loot_template', 3, 'Syntax: .reload creature_loot_template\nReload creature_loot_template table.'),
	('reload creature_questrelation', 3, 'Syntax: .reload creature_questrelation\nReload creature_questrelation table.'),
	('reload disenchant_loot_template', 3, 'Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table.'),
	('reload event_scripts', 3, 'Syntax: .reload event_scripts\nReload event_scripts table.'),
	('reload fishing_loot_template', 3, 'Syntax: .reload fishing_loot_template\nReload fishing_loot_template table.'),
	('reload game_graveyard_zone', 3, 'Syntax: .reload game_graveyard_zone\nReload game_graveyard_zone table.'),
	('reload game_tele', 3, 'Syntax: .reload game_tele\nReload game_tele table.'),
	('reload gameobject_involvedrelation', 3, 'Syntax: .reload gameobject_involvedrelation\nReload gameobject_involvedrelation table.'),
	('reload gameobject_loot_template', 3, 'Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table.'),
	('reload gameobject_questrelation', 3, 'Syntax: .reload gameobject_questrelation\nReload gameobject_questrelation table.'),
	('reload gameobject_scripts', 3, 'Syntax: .reload gameobject_scripts\nReload gameobject_scripts table.'),
	('reload gm_tickets', 3, 'Syntax: .reload gm_tickets\nReload gm_tickets table.'),
	('reload item_enchantment_template', 3, 'Syntax: .reload item_enchantment_template\nReload item_enchantment_template table.'),
	('reload item_loot_template', 3, 'Syntax: .reload item_loot_template\nReload item_loot_template table.'),
	('reload locales_creature', 3, 'Syntax: .reload locales_creature\nReload locales_creature table.'),
	('reload locales_gameobject', 3, 'Syntax: .reload locales_gameobject\nReload locales_gameobject table.'),
	('reload locales_item', 3, 'Syntax: .reload locales_item\nReload locales_item table.'),
	('reload locales_npc_text', 3, 'Syntax: .reload locales_npc_text\nReload locales_npc_text table.'),
	('reload locales_page_text', 3, 'Syntax: .reload locales_page_text\nReload locales_page_text table.'),
	('reload locales_points_of_interest', 3, 'Syntax: .reload locales_points_of_interest\nReload locales_point_of_interest table.'),
	('reload locales_quest', 3, 'Syntax: .reload locales_quest\nReload locales_quest table.'),
	('reload milling_loot_template', 3, 'Syntax: .reload milling_loot_template\nReload milling_loot_template table.'),
	('reload npc_trainer', 3, 'Syntax: .reload npc_trainer\nReload npc_trainer table.'),
	('reload npc_vendor', 3, 'Syntax: .reload npc_vendor\nReload npc_vendor table.'),
	('reload page_text', 3, 'Syntax: .reload page_text\nReload page_text table.'),
	('reload pickpocketing_loot_template', 3, 'Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table.'),
	('reload points_of_interest', 3, 'Syntax: .reload points_of_interest\nReload points_of_interest table.'),
	('reload prospecting_loot_template', 3, 'Syntax: .reload prospecting_loot_template\nReload prospecting_loot_template table.'),
	('reload quest_end_scripts', 3, 'Syntax: .reload quest_end_scripts\nReload quest_end_scripts table.'),
	('reload mail_loot_template', 3, 'Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table.'),
	('reload quest_start_scripts', 3, 'Syntax: .reload quest_start_scripts\nReload quest_start_scripts table.'),
	('reload quest_template', 3, 'Syntax: .reload quest_template\nReload quest_template table.'),
	('reload reference_loot_template', 3, 'Syntax: .reload reference_loot_template\nReload reference_loot_template table.'),
	('reload reserved_name', 3, 'Syntax: .reload reserved_name\nReload reserved_name table.'),
	('reload skill_discovery_template', 3, 'Syntax: .reload skill_discovery_template\nReload skill_discovery_template table.'),
	('reload skill_extra_item_template', 3, 'Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table.'),
	('reload skill_fishing_base_level', 3, 'Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table.'),
	('reload skinning_loot_template', 3, 'Syntax: .reload skinning_loot_template\nReload skinning_loot_template table.'),
	('reload spell_area', 3, 'Syntax: .reload spell_area\nReload spell_area table.'),
	('reload spell_bonus_data', 3, 'Syntax: .reload spell_bonus_data\nReload spell_bonus_data table.'),
	('reload disables', 3, 'Syntax: .reload disables\r\nReload disables table.'),
	('reload spell_group_stack_rules', 3, 'Syntax: .reload spell_group\nReload spell_group_stack_rules table.'),
	('reload spell_learn_spell', 3, 'Syntax: .reload spell_learn_spell\nReload spell_learn_spell table.'),
	('reload spell_linked_spell', 3, 'Usage: .reload spell_linked_spell\r\nReloads the spell_linked_spell DB table.'),
	('reload spell_loot_template', 3, 'Syntax: .reload spell_loot_template\nReload spell_loot_template table.'),
	('reload spell_pet_auras', 3, 'Syntax: .reload spell_pet_auras\nReload spell_pet_auras table.'),
	('reload spell_proc_event', 3, 'Syntax: .reload spell_proc_event\nReload spell_proc_event table.'),
	('reload spell_required', 3, 'Syntax: .reload spell_required\nReload spell_required table.'),
	('reload item_set_names', 3, 'Syntax: .reload item_set_names\nReload item_set_names table.'),
	('reload spell_scripts', 3, 'Syntax: .reload spell_scripts\nReload spell_scripts table.'),
	('reload spell_target_position', 3, 'Syntax: .reload spell_target_position\nReload spell_target_position table.'),
	('reload spell_threats', 3, 'Syntax: .reload spell_threats\nReload spell_threats table.'),
	('reload trinity_string', 3, 'Syntax: .reload trinity_string\nReload trinity_string table.'),
	('reload waypoint_scripts', 3, 'Syntax: .reload waypoint_scripts\nReload waypoint_scripts table.'),
	('reload', 3, 'Syntax: .reload $subcommand\nType .reload to see the list of possible subcommands or .help reload $subcommand to see info on subcommands'),
	('repairitems', 0, 'Syntax: .repairitems\r\n\r\nRepair all selected player\'s items.'),
	('reset achievements', 3, 'Syntax: .reset achievements [$playername]\r\n\r\nReset achievements data for selected or named (online or offline) character. Achievements for persistance progress data like completed quests/etc re-filled at reset. Achievements for events like kills/casts/etc will lost.'),
	('reset all', 3, 'Syntax: .reset all spells\r\n\r\nSyntax: .reset all talents\r\n\r\nRequest reset spells or talents (including talents for all character\'s pets if any) at next login each existed character.'),
	('reset honor', 3, 'Syntax: .reset honor [Playername]\r\n  Reset all honor data for targeted character.'),
	('reset level', 3, 'Syntax: .reset level [Playername]\r\n  Reset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.'),
	('reset spells', 3, 'Syntax: .reset spells [Playername]\r\n  Removes all non-original spells from spellbook.\r\n. Playername can be name of offline character.'),
	('reset stats', 3, 'Syntax: .reset stats [Playername]\r\n  Resets(recalculate) all stats of the targeted player to their original VALUESat current level.'),
	('reset talents', 3, 'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player or pet or named player. Playername can be name of offline character. With player talents also will be reset talents for all character\'s pets if any.'),
	('reset', 0, 'Syntax: .reset $subcommand\nType .reset to see the list of possible subcommands or .help reset $subcommand to see info on subcommands'),
	('respawn', 1, 'Syntax: .respawn\r\n\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.'),
	('revive', 0, 'Syntax: .revive\r\n\r\nRevive the selected player. If no player is selected, it will revive you.'),
	('server save', 0, 'Syntax: .save\r\n\r\nSaves your character.'),
	('server saveall', 1, 'Syntax: .saveall\r\n\r\nSave all characters in game.'),
	('send items', 0, 'Syntax: .send items #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to a player. Subject and mail text must be in "". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.'),
	('send mail', 0, 'Syntax: .send mail #playername "#subject" "#text"\r\n\r\nSend a mail to a player. Subject and mail text must be in "".'),
	('send message', 3, 'Syntax: .send message $playername $message\r\n\r\nSend screen message to player from ADMINISTRATOR.'),
	('send money', 3, 'Syntax: .send money #playername "#subject" "#text" #money\r\n\r\nSend mail with money to a player. Subject and mail text must be in "".'),
	('server corpses', 2, 'Syntax: .server corpses\r\n\r\nTriggering corpses expire check in world.'),
	('server exit', 4, 'Syntax: .server exit\r\n\r\nTerminate trinity-core NOW. Exit code 0.'),
	('server idlerestart cancel', 3, 'Syntax: .server idlerestart cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server idlerestart', 3, 'Syntax: .server idlerestart #delay\r\n\r\nRestart the server after #delay seconds if no active connections are present (no players). Use #exist_code or 2 as program exist code.'),
	('server idleshutdown cancel', 3, 'Syntax: .server idleshutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server idleshutdown', 3, 'Syntax: .server idleshutdown #delay [#exist_code]\r\n\r\nShut the server down after #delay seconds if no active connections are present (no players). Use #exist_code or 0 as program exist code.'),
	('server info', 0, 'Syntax: .server info\r\n\r\nDisplay server version and the number of connected players.'),
	('server motd', 0, 'Syntax: .server motd\r\n\r\nShow server Message of the day.'),
	('server plimit', 3, 'Syntax: .server plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\n\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file'),
	('server restart cancel', 3, 'Syntax: .server restart cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server restart', 3, 'Syntax: .server restart #delay\r\n\r\nRestart the server after #delay seconds. Use #exist_code or 2 as program exist code.'),
	('server set closed', 3, 'Syntax: server set closed on/off\r\n\r\nSets whether the world accepts new client connectsions.'),
	('server set loglevel', 4, 'Syntax: .server set loglevel #level\r\n\r\nSet server log level (0 - errors only, 1 - basic, 2 - detail, 3 - debug).'),
	('server set motd', 3, 'Syntax: .server set motd $MOTD\r\n\r\nSet server Message of the day.'),
	('server shutdown cancel', 3, 'Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.'),
	('server shutdown', 3, 'Syntax: .server shutdown #delay [#exit_code]\r\n\r\nShut the server down after #delay seconds. Use #exit_code or 0 as program exit code.'),
	('server', 3, 'Syntax: .server $subcommand\nType .server to see the list of possible subcommands or .help server $subcommand to see info on subcommands'),
	('setskill', 0, 'Syntax: .setskill #skill #level [#max]\r\n\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.'),
	('showarea', 0, 'Syntax: .showarea #areaid\r\n\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.'),
	('start', 0, 'Syntax: .start\r\n\r\nTeleport you to the starting area of your character.'),
	('taxicheat', 1, 'Syntax: .cheat taxi on/off\r\n\r\nTemporary grant access or remove to all taxi routes for the selected character. If no character is selected, hide or reveal all routes to you.\r\n\r\nVisited taxi nodes sill accessible after removing access.'),
	('recall add', 0, 'Syntax:.recall add $name\r\n\r\nAdd current your position to .tele command target locations list with name $name.'),
	('recall delete', 0, 'Syntax:.recall delete $name\r\n\r\nRemove location with name $name for .tele command locations list.'),
	('recall portus', 0, 'Syntax: .recall portus #location\r\n\r\nTeleport a selected player and his group members to a given location.'),
	('recall portplayer', 0, 'Syntax: .recall portplayer [#playername] #location\r\n\r\nTeleport the given character to a given location. Character can be offline.'),
	('recall', 0, 'Syntax: .recall port #location\r\n\r\nTeleport player to a given location.'),
	('ticket assign', 1, 'Usage: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.'),
	('ticket close', 1, 'Usage: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.'),
	('ticket closedlist', 1, 'Displays a list of closed GM tickets.'),
	('ticket comment', 1, 'Usage: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.'),
	('ticket delete', 3, 'Usage: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.'),
	('ticket list', 1, 'Displays a list of open GM tickets.'),
	('ticket onlinelist', 1, 'Displays a list of open GM tickets whose owner is online.'),
	('ticket unassign', 1, 'Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.'),
	('ticket viewid', 1, 'Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('ticket viewname', 1, 'Usage: .ticket viewname $creatorname. \r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('ticket', 1, 'Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands'),
	('unaura', 0, 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.'),
	('unban account', 3, 'Syntax: .unban account $Name\r\nUnban accounts for account name pattern.'),
	('unban character', 3, 'Syntax: .unban character $Name\r\nUnban accounts for character name pattern.'),
	('unban ip', 3, 'Syntax : .unban ip $Ip\r\nUnban accounts for IP pattern.'),
	('unban', 3, 'Syntax: .unban $subcommand\nType .unban to see the list of possible subcommands or .help unban $subcommand to see info on subcommands'),
	('unbindsight', 3, 'Syntax: .unbindsight\r\n\r\nRemoves bound vision. Cannot be used while currently possessing a target.'),
	('unfreeze', 1, 'Syntax: .unfreeze (#player)\r\n"Unfreezes" #player and enables his chat again. When using this without #name it will unfreeze your target.'),
	('unlearn', 3, 'Syntax: .unlearn #spell [all]\r\n\r\nUnlearn for selected player a spell #spell.  If \'all\' provided then all ranks unlearned.'),
	('unmute', 1, 'Syntax: .unmute [$playerName]\r\n\r\nRestore chat messaging for any character from account of character $playerName (or selected). Character can be ofline.'),
	('unpossess', 3, 'Syntax: .unpossess\r\n\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.'),
	('cheat waterwalk', 2, 'Syntax: .cheat waterwalk on/off\r\n\r\nSet on/off waterwalk state for selected player or self if no player selected.'),
	('modify weather', 3, 'Syntax: .wchange #weathertype #status\r\n\r\nSet current weather to #weathertype with an intensity of #status.\r\n\r\n#weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.'),
	('waypoint event', 2, 'Syntax: .wp event $subcommand\nType .path event to see the list of possible subcommands or .help path event $subcommand to see info on subcommands.'),
	('waypoint load', 2, 'Syntax: .wp load $pathid\nLoad pathid number for selected creature. Creature must have no waypoint data.'),
	('waypoint show', 2, 'Syntax: .wp show $option\nOptions:\non $pathid (or selected creature with loaded path) - Show path\noff - Hide path\ninfo $slected_waypoint - Show info for selected waypoint.'),
	('waypoint unload', 2, 'Syntax: .wp unload\nUnload path for selected creature.'),
	('account expansion', 1, 'Syntax: .account addon #addon\nSet expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk.'),
	('title remove', 0, 'Syntax: .titles remove #title\r\nRemove title #title (id or shift-link) from known titles list for selected player.'),
	('title current', 0, 'Syntax: .titles current #title\r\nSet title #title (id or shift-link) as current selected titl for selected player. If title not in known title list for player then it will be added to list.'),
	('title add', 0, 'Syntax: .titles add #title\r\nAdd title #title (id or shift-link) to known titles list for selected player.'),
	('title set mask', 0, 'Syntax: .titles set mask #mask\r\n\r\nAllows user to use all titles from #mask.\r\n\r\n #mask=0 disables the title-choose-field'),
	('lookup title', 0, 'Syntax: .lookup title $$namepart\r\n\r\nLooks up a title by $namepart, and returns all matches with their title ID\'s and index\'s.'),
	('channel set ownership', 3, 'Syntax: .channel set ownership $channel [on/off]\n\nGrant ownership to the first person that joins the channel.'),
	('reload creature_template', 3, 'Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template.'),
	('character deleted delete', 2, 'Syntax: .character deleted delete #guid|$name\r\n\r\nCompletely deletes the selected characters.\r\nIf $name is supplied, only characters with that string in their name will be deleted, if #guid is supplied, only the character with that GUID will be deleted.'),
	('reload creature_onkill_reputation', 3, 'Syntax: .reload creature_onkill_reputation\r\nReload creature_onkill_reputation table.'),
	('reload conditions', 3, 'Reload conditions table.'),
	('reload locales_item_set_name', 3, 'Syntax: .reload locales_item_set_name\nReload locales_item_set_name table.'),
	('character deleted list', 2, 'Syntax: .character deleted list [#guid|$name]\r\n\r\nShows a list with all deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be selected, if #guid is supplied, only the character with that GUID will be selected.'),
	('character deleted old', 2, 'Syntax: .character deleted old [#keepDays]\r\n\r\nCompletely deletes all characters with deleted time longer #keepDays. If #keepDays not provided the  used value from mangosd.conf option \'CharDelete.KeepDays\'. If referenced config option disabled (use 0 value) then command can\'t be used without #keepDays.'),
	('character deleted restore', 2, 'Syntax: .character deleted restore #guid|$name [$newname] [#new account]\r\n\r\nRestores deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be restored, if $guid is supplied, only the character with that GUID will be restored.\r\nIf $newname is set, the character will be restored with that name instead of the original one. If #newaccount is set, the character will be restored to specific account character list. This works only with one character!'),
	('reload gossip_menu', 3, 'Syntax: .reload gossip_menu\nReload gossip_menu table.'),
	('reload gossip_menu_option', 3, 'Syntax: .reload gossip_menu_option\nReload gossip_menu_option table.'),
	('reload all scripts', 3, 'Syntax: .reload all scripts\nReload gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables.'),
	('reload locales_gossip_menu_option', 3, 'Syntax: .reload locales_gossip_menu_option\nReload locales_gossip_menu_option table.'),
	('reload quest_poi', 3, 'Syntax: .reload quest_poi\nReload quest_poi table.'),
	('reload lfg_dungeon_rewards', 3, 'Syntax: .reload lfg_dungeon_rewards\nReload lfg_dungeon_rewards table.'),
	('character changefaction', 0, 'Syntax: .character changefaction $name\r\n\r\nChange character faction.'),
	('character changerace', 0, 'Syntax: .character changerace $name\r\n\r\nChange character race.'),
	('ban playeraccount', 3, 'Syntax: .ban playeraccount $Name $bantime $reason\nBan account and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like "4d20h3s".'),
	('achievement add', 0, 'Syntax: .achievement add $achievement\nAdd an achievement to the targeted player.\n$achievement: can be either achievement id or achievement link'),
	('achievement', 0, 'Syntax: .achievement $subcommand\nType .achievement to see the list of possible subcommands or .help achievement $subcommand to see info on subcommands'),
	('reload creature_text', 3, 'Syntax: .reload creature_text\r\nReload creature_text table.'),
	('debug areatriggers', 1, 'Syntax: .debug areatriggers\nToggle debug mode for areatriggers. In debug mode GM will be notified if reaching an areatrigger'),
	('learn all recipes', 0, 'Syntax: .learn all recipes [$profession]\r\rLearns all recipes of specified profession and sets skill level to max.\rExample: .learn all recipes enchanting'),
	('npc set spawndist', 2, 'Syntax: .npc set spawndist #dist\r\n\r\nAdjust spawndistance of selected creature to dist.'),
	('npc set spawntime', 2, 'Syntax: .npc set spawntime #time \r\n\r\nAdjust spawntime of selected creature to time.'),
	('npc spawn', 0, 'Syntax: .npc add temp\r\n\r\nAdds temporary NPC, not saved to database.'),
	('npc textemote', 0, 'Syntax: .npc textemote #emoteid\r\n\r\nMake the selected creature to do textemote with an emote of id #emoteid.'),
	('npc whisper', 0, 'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.'),
	('npc yell', 0, 'Syntax: .npc yell $message\nMake selected creature yell specified message.'),
	('waypoint add', 2, 'Syntax: .wp add\r\n\r\nAdd a waypoint for the selected creature at your current position.'),
	('reload all spell', 3, 'Syntax: .reload all spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.'),
	('server togglequerylog', 4, 'Toggle SQL driver query logging.'),
	('reload access_requirement', 3, 'Syntax: .reload access_requirement\nReload access_requirement table.'),
	('reload achievement_criteria_data', 3, 'Syntax: .reload achievement_criteria_data\nReload achievement_criteria_data table.'),
	('reload achievement_reward', 3, 'Syntax: .reload achievement_reward\nReload achievement_reward table.'),
	('reload all achievement', 3, 'Syntax: .reload all achievement\r\n\r\nReload achievement_reward, achievement_criteria_data tables.'),
	('reload all area', 3, 'Syntax: .reload all area\r\n\r\nReload areatrigger_teleport, areatrigger_tavern, game_graveyard_zone tables.'),
	('reload all eventai', 3, 'Syntax: .reload all eventai\r\n\r\nReload creature_ai_scripts, creature_ai_summons, creature_ai_texts tables.'),
	('reload auctions', 3, 'Syntax: .reload auctions\nReload dynamic data tables from the database.'),
	('reload mail_level_reward', 3, 'Syntax: .reload mail_level_reward\nReload mail_level_reward table.'),
	('reload smart_scripts', 3, 'Syntax: .reload smart_scripts\nReload smart_scripts table.'),
	('reload vehicle_accessory', 3, 'Syntax: .reload vehicle_accessory\n\nReloads GUID-based vehicle accessory definitions from the database.'),
	('reload vehicle_template_accessory', 3, 'Syntax: .reload vehicle_template_accessory\n\nReloads entry-based vehicle accessory definitions from the database.'),
	('server disable', 2, 'Syntax: .server disable #IDtype, ID, comment. Type .server disable 2 2 0 for a list of types.'),
	('nudge y', 0, 'Syntax: .nudge y \r\nMoves you 3 units over on the Y axis.'),
	('nudge z', 0, 'Syntax: .nudge x $direction, $direction can be either "up" or "down" \r\nMoves you 3 units on the Z axis in $direction');
/*!40000 ALTER TABLE `command` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
